name = "ILog2"
uuid = "2cd5bd5f-40a1-5050-9e10-fc8cdb6109f5"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com>"]
version = "2.0.0"

[compat]
Aqua = ">= 0.8"
julia = "1"
JET = ">= 0.0"
Test = ">= 0.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "JET"]
